### PR TITLE
Adding network throttling

### PR DESCRIPTION
**Pull request by m0bileDev**
Adding network throttling to avoid putting a burden on servers and drawing attention.

### CODE REVIEW

**Comment by m0bileDev** [comment]
Still a work in progress.

**Comment by knowbee** [comment]
Are you still working on the feature ?

**Comment by m0bileDev** [comment]
> Are you still working on the feature ?

Yes, had to pause but will resume and finish it this weekend so you can code review it.

**Comment by knowbee** [comment]
> > Are you still working on the feature ?
> 
> Yes, had to pause but will resume and finish it this weekend so you can code review it.

Great

**Comment by m0bileDev** [comment]
Finally was able to get back to this, the PR is ready.

Generates a random wait time from min, max set from CLI option. Prints the delay wait time, waits, then clears the wait message so that the screen isn't littered with wait messages. Uses escape sequences for cursor movements.

**Comment by knowbee** [comment]
LGTM

**Pull request merged**
